services:
  app:
    build: .
    command: [python3, /app/shurl/app.py]
    stdin_open: true
    tty: true
    volumes:
      - $PWD:/app

  test:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: [poetry, run, pytest, -vv]
